Algoritmo "JogoDaVelha"
Var
   jg: vetor[1..3,1..3] de caracter
   i, j, esc: inteiro
Inicio
      Para i de 1 ate 3 faca
   EscrevaL("| 1 | 2 | 3 |")
   EscrevaL("+---+---+---+")
   EscrevaL("| 4 | 5 | 6 |")
   EscrevaL("+---+---+---+")
   EscrevaL("| 7 | 8 | 9 |")

   Escolha (esc)
   Caso 1
   Caso 2
   Caso 3
   Caso 4
   Caso 5
   Caso 6
   Enquanto (esc >= 1 e esc <= 9) faca
      Escreva("Vai jogar [X] em qual posicao?")
      Leia(esc)
      Escreva("Vai jogar [0] em qual posicao?")
      Leia(esc)
   FimEnquanto

FimAlgoritmo